In [2]:
import pandas as pd
import datetime
import openpyxl

In [3]:
#infections Denmark

infection_denmark = pd.read_csv("data/teamproject/confirmed_cases_denmark_per_region.csv",  encoding= 'unicode_escape', delimiter=";")
pop_den = pd.read_csv("data/pop_den.csv",  encoding= 'unicode_escape', delimiter=",")


infection_denmark = infection_denmark.rename(columns={"Region" : "region", "Prøvetagningsdato": "date", "Køn" : "gender", "Bekræftede tilfælde" : "confirmed_cases", "Døde" : "deaths"})
infection_denmark = infection_denmark.iloc[: , 0 : 5]

pop_den = pop_den.rename(columns={"ï»¿region" : "region"}) 
pop_den = pop_den.replace(['SjÃ¦lland'],'Sjælland')


#Merge the population dataset with the infection dataset
infection_denmark = pd.merge(pop_den,infection_denmark,on='region')   

   
infection_denmark = infection_denmark.groupby(['date', 'region', 'population'], as_index=False).sum();

infection_denmark['confirmed_cases'] = infection_denmark['confirmed_cases'] / infection_denmark['population'] * 100000;
infection_denmark['deaths'] = infection_denmark['deaths'] / infection_denmark['population'] * 100000;

infection_denmark = infection_denmark.rename(columns={"confirmed_cases" : "confirmed_cases_per_100k"}) 
infection_denmark = infection_denmark.rename(columns={"deaths" : "deaths_per_100k"}) 
print(infection_denmark[0:10])

        date       region  population  confirmed_cases_per_100k  \
0   1-1-2021  Hovedstaden     1846023                 30.985529
1   1-1-2021  Midtjylland     1333245                 17.326148
2   1-1-2021  Nordjylland      589755                 15.769260
3   1-1-2021     Sjælland     2319705                  5.992141
4   1-1-2021   Syddanmark     1223634                 13.647872
5  1-10-2020  Hovedstaden     1846023                  8.883963
6  1-10-2020  Midtjylland     1333245                  8.100537
7  1-10-2020  Nordjylland      589755                  6.952039
8  1-10-2020     Sjælland     2319705                  2.414100
9  1-10-2020   Syddanmark     1223634                  4.739979

   deaths_per_100k
0         0.650046
1         0.150010
2         0.339124
3         0.086218
4         0.163448
5         0.000000
6         0.075005
7         0.508686
8         0.000000
9         0.081724

In [4]:
#infection USA per state

#Import the datasets
infection_usa = pd.read_csv("data/teamproject/usa_cases.csv",  encoding= 'unicode_escape', delimiter=",")
pop_usa = pd.read_csv("data/pop_usa.csv",  encoding= 'unicode_escape', delimiter=",")


#Replace the statenames by the statecodes
pop_usa = pop_usa.replace({
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
})


infection_usa = infection_usa.iloc[: , [0, 1, 5]]
infection_usa = infection_usa.rename(columns={"submission_date" : "date"})

pop_usa = pop_usa.iloc[5 : , [4, 5]]
pop_usa = pop_usa.rename(columns={"NAME" : "state", "CENSUS2010POP" : "population"})

#Merge the population dataset with the infection dataset
infection_usa = pd.merge(pop_usa,infection_usa,on='state')

#Change the date
infection_usa['date'] =  pd.to_datetime(infection_usa['date'])
infection_usa['date'] = pd.to_datetime(infection_usa['date'], format='%Y%m%d').dt.strftime('%d/%m/%Y')

#Grouping the states and dates together
infection_usa = infection_usa.groupby(['date', 'state', 'new_case'], as_index=False).sum();

#Calculate the infections per 100k
infection_usa['new_case'] = infection_usa['new_case'] / infection_usa['population'] * 100000;

infection_usa = infection_usa.rename(columns={"new_case" : "new_cases_per_100k"})


infection_usa

             date state  new_cases_per_100k  population
0      01/01/2021    AK           66.175653      710231
1      01/01/2021    AL           48.454559     4779736
2      01/01/2021    AR          147.603602     2915918
3      01/01/2021    AZ          157.430745     6392017
4      01/01/2021    CA          151.683220    37253956
...           ...   ...                 ...         ...
32287  31/12/2020    VT           22.053853      625741
32288  31/12/2020    WA           58.859045     6724540
32289  31/12/2020    WI           74.063836     5686986
32290  31/12/2020    WV           59.849087     1852994
32291  31/12/2020    WY           48.968642      563626

[32292 rows x 4 columns]

In [5]:
#infection_england_region

infection_eng = pd.read_csv("data/teamproject/infection_region_eng.csv",  encoding= 'unicode_escape', delimiter=",")

#infection_nation_uk = pd.read_csv("data/teamproject/infections_nation_uk.csv",  encoding= 'unicode_escape', delimiter=",")
#infection_nation_uk = infection_nation_uk.iloc[: , [1, 2, 3, 4]]
#print(infection_nation_uk)

pop_uk = pd.read_csv("data/pop_uk.csv",  encoding= 'unicode_escape', delimiter=",")

infection_eng = infection_eng.rename(columns=str.lower)

infection_eng = infection_eng.iloc[: , [1, 3, 4]]

pop_uk = pop_uk.rename(columns={"ï»¿areaname" : "areaname"})


#Change the date
infection_eng['date'] =  pd.to_datetime(infection_eng['date'])
infection_eng['date'] = pd.to_datetime(infection_eng['date'], format='%Y%m%d').dt.strftime('%d/%m/%Y')

infection_eng = pd.merge(pop_uk,infection_eng,on='areaname')

#Calculate the infections per 100k
infection_eng['cases_per_100k'] = infection_eng['newcasesbypublishdate'] / infection_eng['population'] * 100000;

infection_eng = infection_eng.sort_values(by="date")

print(infection_eng.iloc[:10])

             areaname  population        date  newcasesbypublishdate  \
2420       North West     7300000  01/01/2021                   5164
276     East Midlands     4533000  01/01/2021                   3079
4028    West Midlands     2928000  01/01/2021                   2860
1348           London     8899375  01/01/2021                  15089
1884       North East     2597000  01/01/2021                   1340
2956       South East     9175000  01/01/2021                  10844
3492       South West     5616000  01/01/2021                   2104
812   East of England     5847000  01/01/2021                   7640
245     East Midlands     4533000  01/02/2021                   1617
2925       South East     9175000  01/02/2021                   2350

      cases_per_100k
2420       70.739726
276        67.924112
4028       97.677596
1348      169.551233
1884       51.597998
2956      118.190736
3492       37.464387
812       130.665298
245        35.671741
2925       25.613079

In [6]:
#Denmark Vaccination

vacc_den = pd.read_csv("data/teamproject/vacc_den.csv",  encoding= 'unicode_escape', delimiter=",")
vacc_den = vacc_den.rename(columns=str.lower)

#Choose correct columns
vacc_den = vacc_den.iloc[: , [0, 1, 2, -1]]

#Strip %
vacc_den['percentage_finished vaccinated'] = vacc_den['percentage_finished vaccinated'].str.replace(r'%', '')


#Group vaccination dataset
vacc_den = vacc_den.groupby(['municipality', 'percentage_finished vaccinated', 'ppl_inventory', 'parish'], as_index=False).sum();

#Change datatype of %vaccinated
vacc_den["percentage_finished vaccinated"] = vacc_den["percentage_finished vaccinated"].astype(float, 'raise')


#Calculate the amount of vaccinated people per parish
vacc_den['tot_vacc_parish'] = vacc_den['ppl_inventory'] * (vacc_den['percentage_finished vaccinated'] / 100);

#Group the dataset into municipalities 
vacc_den = vacc_den.groupby(['municipality'], as_index=False).sum(['ppl_inventory', 'tot_vacc_parish']);
vacc_den = vacc_den.iloc[: , [0, 2, 3]]

#Calculate the percentage of infected by municipality 
vacc_den['vacc_pct_municipality'] = vacc_den['tot_vacc_parish'] / vacc_den['ppl_inventory'] * 100

vacc_den = vacc_den.rename(columns={"tot_vacc_parish" : "tot_vacc_municipality"})


print(vacc_den)

       municipality  ppl_inventory  tot_vacc_municipality  \
0          Aabenraa          51431               42751.16
1           Aalborg         194520              168230.09
2            Aarhus         309984              265951.29
3       Albertslund          23466               18002.26
4          AllerÃ¸d          21912               19952.92
..              ...            ...                    ...
93            Vejle         101731               86907.33
94  Vesthimmerlands          31880               27413.51
95           Viborg          83664               73369.07
96      Vordingborg          40651               34463.35
97            ÃrÃ¸           5537                4963.90

    vacc_pct_municipality
0               83.123330
1               86.484727
2               85.795167
3               76.716356
4               91.059328
..                    ...
93              85.428562
94              85.989680
95              87.694911
96              84.778603
97              89.649630

[98 rows x 4 columns]

In [7]:
#USA Vaccination

vacc_usa = pd.read_csv("data/teamproject/vacc_usa.csv",  encoding= 'unicode_escape', delimiter=",")
vacc_usa = vacc_usa.rename(columns=str.lower)

vacc_usa = vacc_usa.rename(columns={"location" : "state"})

vacc_usa = vacc_usa.iloc[: , [0, 2, 42]]

vacc_usa['date'] =  pd.to_datetime(vacc_usa['date'])
vacc_usa['date'] = pd.to_datetime(vacc_usa['date'], format='%Y%m%d').dt.strftime('%d/%m/%Y')

vacc_usa = vacc_usa.groupby(['date', 'state'], as_index=False).sum();


vacc_usa

             date state  series_complete_pop_pct
0      01/01/2021    AK                      0.0
1      01/01/2021    AL                      0.0
2      01/01/2021    AR                      0.0
3      01/01/2021    AS                      0.0
4      01/01/2021    AZ                      0.0
...           ...   ...                      ...
19138  31/12/2020    VT                      0.0
19139  31/12/2020    WA                      0.0
19140  31/12/2020    WI                      0.0
19141  31/12/2020    WV                      0.0
19142  31/12/2020    WY                      0.0

[19143 rows x 3 columns]

In [224]:
#UK vaccination

xls = pd.ExcelFile('data/teamproject/vacc_uk.xlsx')
vacc_eng = pd.read_excel(xls, '1f')

vacc_wales = pd.read_excel(xls, '2d')

vacc_north_ireland = pd.read_excel(xls, '3d')

vacc_scotland = pd.read_excel(xls, '4d')

#vacc_eng = vacc_eng.iloc[3: 42 , [0, 1, 6, 15 ] ]
vacc_wales = vacc_wales.iloc[3: 41 , ]
vacc_north_ireland = vacc_north_ireland.iloc[3: 40 , ]
vacc_scotland = vacc_scotland.iloc[3: 41 , ]


#vacc_eng = vacc_eng.reset_index(drop=True)
vacc_eng.columns = range(vacc_eng.shape[1])

vacc_wales = vacc_wales.reset_index(drop=True)
vacc_wales.columns = range(vacc_wales.shape[1])

vacc_north_ireland = vacc_north_ireland.reset_index(drop=True)
vacc_north_ireland.columns = range(vacc_north_ireland.shape[1])

vacc_scotland_scotland = vacc_scotland.reset_index(drop=True)
vacc_scotland.columns = range(vacc_scotland.shape[1])


vacc_wales = vacc_wales.iloc[: , [0, 6]]
vacc_north_ireland = vacc_north_ireland.iloc[: , [0, 6]]
vacc_scotland = vacc_scotland.iloc[: , [0, 5, 6]]

#print(vacc_scotland)

vacc_eng2 = pd.merge(vacc_eng,vacc_wales ,on=[0]) 
vacc_eng2 = pd.merge(vacc_eng2,vacc_north_ireland ,on=[0])
vacc_eng2 = pd.merge(vacc_eng2,vacc_scotland ,on=[0]) 


vacc_eng2.columns = range(vacc_eng2.shape[1])


vacc_eng.at[4, 0] = 'weekly_period_end'
vacc_eng.at[4, 6] = "full_vacc_north_east"
vacc_eng.at[4, 16] = "full_vacc_north_west"
vacc_eng.at[4, 26] = "full_vacc_yorkshire_and_the_humber"
vacc_eng.at[4, 36] = "full_vacc_east_midlands"
vacc_eng.at[4, 46] = "full_vacc_west_midlands"
vacc_eng.at[4, 56] = "full_vacc_east_of_england"
vacc_eng.at[4, 66] = "full_vacc_london"
vacc_eng.at[4, 76] = "full_vacc_south_east"
vacc_eng.at[4, 86] = "full_vacc_south_west"


vacc_eng2.at[0, 0] = 'weekly_period_end'
vacc_eng2.at[0, 6] = "full_vacc_north_east"
vacc_eng2.at[0, 16] = "full_vacc_north_west"
vacc_eng2.at[0, 26] = "full_vacc_yorkshire_and_the_humber"
vacc_eng2.at[0, 36] = "full_vacc_east_midlands"
vacc_eng2.at[0, 46] = "full_vacc_west_midlands"
vacc_eng2.at[0, 56] = "full_vacc_east_of_england"
vacc_eng2.at[0, 66] = "full_vacc_london"
vacc_eng2.at[0, 76] = "full_vacc_south_east"
vacc_eng2.at[0, 86] = "full_vacc_south_west"
vacc_eng2.at[0, 91] = "full_vacc_wales"
vacc_eng2.at[0, 92] = "full_vacc_north_ireland"
vacc_eng2.at[0, 94] = "full_vacc_scotland"




vacc_eng = vacc_eng.iloc[4 : 42 , [0, 6, 16, 26, 36, 46, 56, 66, 76, 86]]
vacc_eng2 = vacc_eng2.iloc[: , [0, 6, 16, 26, 36, 46, 56, 66, 76, 86, 91, 92, 94]]



vacc_eng.columns = range(vacc_eng.shape[1])
vacc_eng = vacc_eng.reset_index(drop=True)

vacc_eng2.columns = range(vacc_eng2.shape[1])
vacc_eng2 = vacc_eng2.reset_index(drop=True)



new_header = vacc_eng.iloc[0] #grab the first row for the header
vacc_eng = vacc_eng[1:] #take the data less the header row
vacc_eng.columns = new_header #set the header row as the df header

new_header2 = vacc_eng2.iloc[0] #grab the first row for the header
vacc_eng2 = vacc_eng2[1:] #take the data less the header row
vacc_eng2.columns = new_header2 #set the header row as the df header


vacc_eng = vacc_eng.replace(['-'], 0)
vacc_eng2 = vacc_eng2.replace(['-'], 0)


vacc_eng['weekly_period_end'] = vacc_eng.weekly_period_end.replace({"December" : '12',
 "January" : "01",
 "February" : '02',
 "March" : "03",
 "April" : '04',
 "May" : "05",
 "June" : "06",
 "July" : '07',
 "August" : '08',
 " " : "-",       
}, regex = True).astype(str)


vacc_eng2['weekly_period_end'] = vacc_eng2.weekly_period_end.replace({"December" : '12',
 "January" : "01",
 "February" : '02',
 "March" : "03",
 "April" : '04',
 "May" : "05",
 "June" : "06",
 "July" : '07',
 "August" : '08',
 " " : "-",       
}, regex = True).astype(str)




vacc_eng['weekly_period_end'] = vacc_eng['weekly_period_end'].str.split("-to-").str[1]
vacc_eng2['weekly_period_end'] = vacc_eng2['weekly_period_end'].str.split("-to-").str[1]


vacc_eng2.to_csv('data/full_uk_vacc.csv', sep=',', encoding='utf-8')

/tmp/ipykernel_60/1660804255.py:39: FutureWarning: Passing 'suffixes' which cause duplicate columns {'6_x'} in the result is deprecated and will raise a MergeError in a future version.
  vacc_eng2 = pd.merge(vacc_eng2,vacc_scotland ,on=[0])