In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine, inspect, Table

In [2]:
dfplot = pd.read_csv('tweetid_userid_keyword_sentiments_emotions_United States.csv', nrows=9999)
dfplot

,tweet_id,user_id,tweet_timestamp,keyword,valence_intensity,fear_intensity,anger_intensity,happiness_intensity,sadness_intensity,sentiment,emotion
0,1221958334661779458,18527874,2020-01-27 16-49-04,wuhan,0.513,0.550,0.358,0.364,0.344,neutral or mixed,no specific emotion
1,1221959351461720064,35527998,2020-01-27 16-53-06,wuhan,0.526,0.387,0.421,0.364,0.368,positive,happiness
2,1221959956951224320,415915436,2020-01-27 16-55-31,wuhan,0.578,0.328,0.280,0.440,0.383,positive,happiness
3,1221961233026281472,22586384,2020-01-27 17-00-35,wuhan,0.497,0.464,0.431,0.339,0.388,neutral or mixed,no specific emotion
4,1221961678058926080,2399087653,2020-01-27 17-02-21,wuhan,0.448,0.449,0.425,0.291,0.474,negative,sadness
...,...,...,...,...,...,...,...,...,...,...,...
9994,1222321710273265670,958672653493194752,2020-01-28 16-53-00,wuhan,0.451,0.392,0.375,0.304,0.366,negative,fear
9995,1222321716367626240,129675254,2020-01-28 16-53-01,corona,0.430,0.583,0.494,0.262,0.445,negative,fear
9996,1222321736923795456,2716895181,2020-01-28 16-53-06,corona,0.446,0.491,0.411,0.286,0.377,negative,fear
9997,1222321803927924738,3091759240,2020-01-28 16-53-22,wuhan,0.376,0.629,0.522,0.232,0.505,negative,fear
9998,1222321848236564482,18146448,2020-01-28 16-53-32,corona,0.371,0.481,0.505,0.241,0.416,negative,anger

In [3]:
# Deleting redundant columns 
dfplot = dfplot.iloc[: , 1:]

# Splitting timestamp and replacing it in df
dfplot['tweet_timestamp'] = dfplot['tweet_timestamp'].str.split(' ').str[0]
dfplot

,user_id,tweet_timestamp,keyword,valence_intensity,fear_intensity,anger_intensity,happiness_intensity,sadness_intensity,sentiment,emotion
0,18527874,2020-01-27,wuhan,0.513,0.550,0.358,0.364,0.344,neutral or mixed,no specific emotion
1,35527998,2020-01-27,wuhan,0.526,0.387,0.421,0.364,0.368,positive,happiness
2,415915436,2020-01-27,wuhan,0.578,0.328,0.280,0.440,0.383,positive,happiness
3,22586384,2020-01-27,wuhan,0.497,0.464,0.431,0.339,0.388,neutral or mixed,no specific emotion
4,2399087653,2020-01-27,wuhan,0.448,0.449,0.425,0.291,0.474,negative,sadness
...,...,...,...,...,...,...,...,...,...,...
9994,958672653493194752,2020-01-28,wuhan,0.451,0.392,0.375,0.304,0.366,negative,fear
9995,129675254,2020-01-28,corona,0.430,0.583,0.494,0.262,0.445,negative,fear
9996,2716895181,2020-01-28,corona,0.446,0.491,0.411,0.286,0.377,negative,fear
9997,3091759240,2020-01-28,wuhan,0.376,0.629,0.522,0.232,0.505,negative,fear
9998,18146448,2020-01-28,corona,0.371,0.481,0.505,0.241,0.416,negative,anger

In [4]:
# Imports
from sqlalchemy import create_engine, inspect, Table
# Open a connection to the postgresql database
db_conn = create_engine("postgresql://student:infomdss@db_assignments:5432/covid")

In [5]:
db_conn.execute("DROP TABLE IF EXISTS dfplot CASCADE;")

In [6]:
dfplot.to_sql("dfplot", db_conn)

In [7]:
fear = '''
SELECT count(dfplot.emotion) as fear, tweet_timestamp
FROM dfplot
where emotion = 'fear'
group by tweet_timestamp
order by tweet_timestamp


'''

#############################
# Your query is performed on the database to create the view
#if not create_table.isspace():
 #   db_conn.execute(fear)
    
table_fear = pd.read_sql(fear, db_conn)
print(table_fear)
fear = pd.DataFrame(table_fear)
fear

   fear tweet_timestamp
0   276      2020-01-27
1  4575      2020-01-28

   fear tweet_timestamp
0   276      2020-01-27
1  4575      2020-01-28

In [8]:
happiness = '''
SELECT count(dfplot.emotion) as happiness, tweet_timestamp
FROM dfplot
where emotion = 'happiness'
group by tweet_timestamp
order by tweet_timestamp


'''

#############################
# Your query is performed on the database to create the view
#if not create_table.isspace():
 #   db_conn.execute(create_table)
    
table_happiness = pd.read_sql(happiness, db_conn)
print(table_happiness)

happiness = pd.DataFrame(table_happiness)

   happiness tweet_timestamp
0         72      2020-01-27
1       1470      2020-01-28

In [ ]:
sadness = '''
SELECT count(dfplot.emotion) as sadness, tweet_timestamp
FROM dfplot
where emotion = 'sadness'
group by tweet_timestamp
order by tweet_timestamp


'''

#############################
# Your query is performed on the database to create the view
#if not create_table.isspace():
 #   db_conn.execute(sadness)
    
table_sadness = pd.read_sql(sadness, db_conn)
print(table_sadness)

sadness = pd.DataFrame(table_sadness)
sadness

In [ ]:
no_specific_emotion = '''
SELECT count(dfplot.emotion) as no_specific_emotion, tweet_timestamp
FROM dfplot
where emotion = 'no specific emotion'
group by tweet_timestamp
order by tweet_timestamp


'''

#############################
# Your query is performed on the database to create the view
#if not create_table.isspace():
 #   db_conn.execute(no_specific_emotion)
    
table_no_specific_emotion = pd.read_sql(no_specific_emotion, db_conn)
print(table_no_specific_emotion)

no_specific_emotion = pd.DataFrame(table_no_specific_emotion)

In [ ]:
anger = '''
SELECT count(dfplot.emotion) as anger, tweet_timestamp
FROM dfplot
where emotion = 'anger'
group by tweet_timestamp
order by tweet_timestamp


'''

#############################
# Your query is performed on the database to create the view
#if not create_table.isspace():
 #   db_conn.execute(anger)
    
table_anger = pd.read_sql(anger, db_conn)
print(table_anger)

anger = pd.DataFrame(table_anger)

In [ ]:
df1 = (pd.merge(anger, fear, on='tweet_timestamp'))
df2 = (pd.merge(df1, happiness, on='tweet_timestamp'))
df3 = (pd.merge(df2, no_specific_emotion, on='tweet_timestamp'))
df4 = (pd.merge(df3, sadness, on='tweet_timestamp'))

# to date type
df4['tweet_timestamp'] = pd.to_datetime(df4.tweet_timestamp)
#df4['tweet_timestamp'].dt.strftime("%Y%m%d").astype(int)
#df4['tweet_timestamp'].str.replace("-","").astype(float)
df4.set_index('tweet_timestamp')

df4.to_csv('dfplotframe.csv')

In [ ]:
import calmap
import calplot
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from matplotlib.pyplot import figure

figure(figsize=(12, 15), dpi=80)

x1 = df4.tweet_timestamp 
y1 = df4.fear
y2 = df4.anger
y3 = df4.happiness
y4 = df4.sadness
plt.plot(x1, y1)
plt.plot(x1, y2)
plt.plot(x1, y3)
plt.plot(x1, y4)

plt.legend(["fear ", "anger", "happiness", "sadness"])